"""Caption rendering as an ASS subtitle file.

The subtitle file is burned into the video *while the frame is still the square
viewport*, using ``PlayResX``/``PlayResY`` equal to the viewport size. libass
clips everything to that frame, which is exactly the guarantee the spec wants:
captions can never spill into the black area, and they never inherit the video
layer's zoom because they are drawn after the zoom.
"""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

from .. import colors
from ..captions import Phrase
from ..models import CaptionSettings
from ..timecode import format_ass_time

#: Reference font size the user-facing outline/shadow sliders were tuned at.
_REFERENCE_FONT_SIZE = 62.0


def outline_to_pixels(settings: CaptionSettings) -> float:
    """Map the user-friendly outline value onto libass border pixels.

    The user's existing editor expresses outline as a small number around 0.5.
    libass measures the border in pixels at the current PlayRes, so the value is
    scaled by the font size to keep the same visual weight at any size.
    """
    scaled = settings.outline_width * (settings.font_size / _REFERENCE_FONT_SIZE) * 5.0
    return round(max(0.0, scaled), 2)


def shadow_to_pixels(settings: CaptionSettings) -> float:
    """Hard drop shadow depth in pixels."""
    scaled = (
        settings.shadow_offset
        * settings.shadow_strength
        * (settings.font_size / _REFERENCE_FONT_SIZE)
    )
    return round(max(0.0, scaled), 2)


def _escape(text: str) -> str:
    """Neutralise ASS control characters in user/transcript text."""
    return (
        text.replace("\\", "\u29f5")
        .replace("{", "(")
        .replace("}", ")")
        .replace("\r", " ")
        .replace("\n", " ")
    )


def _highlighted(text: str, settings: CaptionSettings) -> str:
    """Recolour configured keywords inline using ASS colour overrides."""
    if not settings.highlight_keywords:
        return _escape(text)
    base = colors.hex_to_ass(settings.color)
    accent = colors.hex_to_ass(settings.highlight_color)
    out: list[str] = []
    for token in text.split():
        core = token.strip(".,!?:;\"'").lower()
        if core in settings.highlight_keywords:
            out.append(f"{{\\c{accent}}}{_escape(token)}{{\\c{base}}}")
        else:
            out.append(_escape(token))
    return " ".join(out)


def build_ass(
    phrases: Sequence[Phrase],
    settings: CaptionSettings,
    *,
    viewport_size: int,
    font_family: str,
) -> str:
    outline = outline_to_pixels(settings)
    shadow = shadow_to_pixels(settings)
    primary = colors.hex_to_ass(settings.color)
    outline_colour = colors.hex_to_ass(settings.outline_color)
    shadow_colour = colors.hex_to_ass(settings.shadow_color)
    bold = -1 if settings.bold else 0

    header = [
        "[Script Info]",
        "; Generated by Clipforge - do not edit by hand",
        "ScriptType: v4.00+",
        "WrapStyle: 0",
        "ScaledBorderAndShadow: yes",
        "YCbCr Matrix: TV.709",
        f"PlayResX: {viewport_size}",
        f"PlayResY: {viewport_size}",
        "",
        "[V4+ Styles]",
        (
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
            "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, "
            "ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, "
            "MarginL, MarginR, MarginV, Encoding"
        ),
        (
            f"Style: Caption,{font_family},{settings.font_size},{primary},{primary},"
            f"{outline_colour},{shadow_colour},{bold},0,0,0,100,100,0,0,1,"
            f"{outline},{shadow},{settings.ass_alignment()},"
            f"{settings.margin_x},{settings.margin_x},{settings.margin_v},1"
        ),
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]

    events = [
        (
            f"Dialogue: 0,{format_ass_time(p.start)},{format_ass_time(p.end)},"
            f"Caption,,0,0,0,,{_highlighted(p.text, settings)}"
        )
        for p in phrases
        if p.end > p.start and p.text.strip()
    ]
    return "\n".join(header + events) + "\n"


def write_ass(
    phrases: Sequence[Phrase],
    settings: CaptionSettings,
    *,
    destination: Path,
    viewport_size: int,
    font_family: str,
) -> Path:
    destination.write_text(
        build_ass(phrases, settings, viewport_size=viewport_size, font_family=font_family),
        encoding="utf-8",
    )
    return destination
